### ISSUE TITLE
logo

### ISSUE THREAD

**Issue by erikzephyr** [erikzephyr/Dice#2]
el logo es muy feo

**Comment by erikzephyr** [comment]
pues me gusta tu idea

**Comment by erikzephyr** [comment]
a mi tmb

**Comment by richardbmx** [comment]
@erikzephyr  Hi, my name is Richard. I'm a graphic designer and I love making contributions for open source projects. I see that they want a new logo for your application. If you wish, I can do it for you without any problem ... I can present some modern ideas that would improve the appearance and image of your project

**Comment by erikzephyr** [comment]
Hii, I would like to see!! <3

**Comment by richardbmx** [comment]
@erikzephyr  Ok perfect I'm going to work on it

**Comment by richardbmx** [comment]
@erikzephyr  Sorry for the delay had some problems with the network, here I present my proposal is based on a dice to give identity with your project I hope you like it, if you want some change you should just ask

![logo112](https://user-images.githubusercontent.com/35604837/46922262-5ae87400-cfd4-11e8-9ac0-bb438f862c47.png)

**Comment by richardbmx** [comment]
small variation with the center lines

![logo1122](https://user-images.githubusercontent.com/35604837/46922465-89b41980-cfd7-11e8-9e66-8aedb3043991.png)

**Comment by erikzephyr** [comment]
> small variation with the center lines
> 
> ![logo1122](https://user-images.githubusercontent.com/35604837/46922465-89b41980-cfd7-11e8-9e66-8aedb3043991.png)

wow, i loved second design so much, center line was so clean

**Comment by richardbmx** [comment]
@erikzephyr  Perfect I will generate a folder with all the files so you can use the logo

**Comment by richardbmx** [comment]
Si hablas español podemos hablar en español tambien ;-)
